version: '3'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "33000:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  flask-app:
    build: ./app
    restart: always
    ports:
      - "5002:5002"
    depends_on:
      - mysql